version: '3'

services:
  concourse-db:
    container_name: concourse-db
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      PGDATA: /database

  concourse-web:
    container_name: concourse-web
    image: concourse/concourse
    links: [concourse-db]
    command: web
    depends_on: [concourse-db]
    ports:
    - 8080:8080
    - 2222:2222
    volumes:
    - ./keys/web:/concourse-keys
    restart: unless-stopped
    environment:
      CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH: 'true'
      CONCOURSE_EXTERNAL_URL: http://192.168.99.100:8080
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: root
      CONCOURSE_POSTGRES_PASSWORD: admin
      CONCOURSE_POSTGRES_DATABASE: concourse

  concourse-worker-1:
    container_name: concourse-worker-1
    image: concourse/concourse
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    volumes:
    - ./keys/worker:/concourse-keys
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_GARDEN_BTRFS_STORE_SIZE_MB: 10000